# SPDX-FileCopyrightText: 2024 Alec Delaney
# SPDX-License-Identifier: MIT

version: 2

# OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx configuration file
sphinx:
  configuration: docs/conf.py

# Build dependencies
python:
  install:
    - requirements: docs/requirements.txt
